version: 2

jobs:
    build:
        environment:
            TZ: "/usr/share/zoneinfo/America/Detroit"
        working_directory: ~/app/circleci
        docker:
            - image: circleci/openjdk:11.0.1-jdk-sid-node-browsers
        steps:

            ##
            # SETUP
            ##
            - run:
                name: Flag local/PR builds
                command: |
                  if [[ "$CIRCLE_BUILD_NUM" == '' ]]; then
                    touch ~/.localCircleBuild
                  fi
                  if [[ "$CIRCLE_PR_USERNAME" != '' ]]; then
                    touch ~/.prCircleBuild
                  fi
            - add_ssh_keys
            - checkout
            - run:
                name: Install jq
                command: |
                  sudo curl -sSL -o /usr/local/bin/jq https://github.com/stedolan/jq/releases/download/jq-1.5/jq-linux64
                  sudo chmod +x /usr/local/bin/jq
            - run:
                name: Calculate codebase version
                command: |
                  bash .devops/calculate-app-version.sh

            ##
            # RESTORE CACHES
            ##
            - restore_cache:
                key: v1-dependency-cache-{{ checksum "build.gradle" }}
            - restore_cache:
                key: v1-wrapper-cache-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}

            ##
            # GRADLE
            ##
            - run:
                name: Run Unit Tests
                command: |
                  if [[ -f ~/.localCircleBuild ]]; then
                    CIRCLE_LOCAL_BUILD=true
                  else
                    CIRCLE_LOCAL_BUILD=false
                  fi
                  bash .devops/test_and_coverage.sh $CIRCLE_LOCAL_BUILD
            - store_artifacts:
                 path: build/reports/jacoco/test/html
            - run:
                name: Run Whitesource
                command: |
                  set -ou pipefail
                  if [[ ! -f ~/.localCircleBuild && ! -f ~/.prCircleBuild ]]; then
                    bash .devops/whitesource.sh
                  fi

            ##
            # SAVE CACHES
            ##
            - save_cache:
                key: v1-dependency-cache-{{ checksum "build.gradle" }}
                paths:
                    - /home/circleci/.gradle/caches
            - save_cache:
                key: v1-wrapper-cache-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
                paths:
                    - /home/circleci/.gradle/wrapper

            ##
            # DEPLOYMENT
            ##
            - run:
                name: Deploy Beta (master)
                command: |
                  set -ou pipefail
                  if [[ ! -f ~/.localCircleBuild ]]; then
                    if [ "${CIRCLE_BRANCH}" == "master" ]; then
                      bash .devops/deploy.sh beta
                    fi
                  fi
            - run:
                name: Deploy RC (rc)
                command: |
                  set -ou pipefail
                  if [[ ! -f ~/.localCircleBuild ]]; then
                    if [ "${CIRCLE_BRANCH}" == "rc" ]; then
                      bash .devops/deploy.sh rc
                      bash .devops/post-release.sh
                      # Need to checkout rc again so we can run more scripts.
                      git checkout rc
                      bash .devops/updateProdReleasePr.sh
                    fi
                  fi
            - run:
                name: Deploy Production (release)
                command: |
                  set -ou pipefail
                  if [[ ! -f ~/.localCircleBuild ]]; then
                    if [ "${CIRCLE_BRANCH}" == "release" ]; then
                      bash .devops/deploy.sh release
                      bash .devops/post-release.sh
                    fi
                  fi
